/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DUYAN
 */
public class QuanLyDiem extends javax.swing.JFrame {

    int x, y;

    Color panedefault;
    Color paneClick;

    public QuanLyDiem() {
        initComponents();
        setLocationRelativeTo(null);

        panedefault = new Color(0, 204, 204);
        paneClick = new Color(0, 80, 240);
        pane1.setBackground(panedefault);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);

        Home_Jint hm = new Home_Jint();
        jDesktopPane1.add(hm).setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblScreen = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelStudent = new javax.swing.JPanel();
        pane2 = new javax.swing.JPanel();
        lblStudent = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        pane1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jPanelRating = new javax.swing.JPanel();
        pane4 = new javax.swing.JPanel();
        lblRating = new javax.swing.JLabel();
        jPanelLearning = new javax.swing.JPanel();
        pane3 = new javax.swing.JPanel();
        lblLearning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_exit_30px.png"))); // NOI18N
        lblExit.setAutoscrolls(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExitMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Vni 07 WaterBrushROB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_java_30px.png"))); // NOI18N
        jLabel2.setText("Assignment Java3 by DUY AN - PS14885");

        lblScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_screensharing_30px.png"))); // NOI18N
        lblScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblScreenMousePressed(evt);
            }
        });

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_zoom_out_30px.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 964, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMinimize)
                            .addComponent(lblScreen)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1400, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jPanelStudent.setBackground(new java.awt.Color(0, 204, 204));
        jPanelStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelStudentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelStudentMousePressed(evt);
            }
        });
        jPanelStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelStudent.add(pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        lblStudent.setBackground(new java.awt.Color(204, 204, 204));
        lblStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_student_male_30px.png"))); // NOI18N
        lblStudent.setText("Student Manager");
        jPanelStudent.add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanelHome.setBackground(new java.awt.Color(0, 204, 204));
        jPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHomeMousePressed(evt);
            }
        });
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelHome.add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        lblHome.setBackground(new java.awt.Color(204, 204, 204));
        lblHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_home_30px.png"))); // NOI18N
        lblHome.setText("Home");
        jPanelHome.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanelRating.setBackground(new java.awt.Color(0, 204, 204));
        jPanelRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRatingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRatingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRatingMousePressed(evt);
            }
        });
        jPanelRating.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pane4Layout = new javax.swing.GroupLayout(pane4);
        pane4.setLayout(pane4Layout);
        pane4Layout.setHorizontalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pane4Layout.setVerticalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelRating.add(pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        lblRating.setBackground(new java.awt.Color(204, 204, 204));
        lblRating.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_ratings_30px.png"))); // NOI18N
        lblRating.setText("Statistical");
        jPanelRating.add(lblRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        jPanelLearning.setBackground(new java.awt.Color(0, 204, 204));
        jPanelLearning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLearningMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLearningMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLearningMousePressed(evt);
            }
        });
        jPanelLearning.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pane3Layout = new javax.swing.GroupLayout(pane3);
        pane3.setLayout(pane3Layout);
        pane3Layout.setHorizontalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pane3Layout.setVerticalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelLearning.add(pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        lblLearning.setBackground(new java.awt.Color(204, 204, 204));
        lblLearning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLearning.setForeground(new java.awt.Color(255, 255, 255));
        lblLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_study_30px.png"))); // NOI18N
        lblLearning.setText("Learning progress Manage\t\t\t\t\t\t\t\t\t ");
        jPanelLearning.add(lblLearning, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_account_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_settings_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_a_32px_1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_n_32px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WELCOME");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_mail_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelRating, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelRating, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 610));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1160, 593));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 1160, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMousePressed
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_lblExitMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanelHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMousePressed
        pane1.setBackground(paneClick);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);
        Home_Jint hm = new Home_Jint();
        jDesktopPane1.add(hm).setVisible(true);
    }//GEN-LAST:event_jPanelHomeMousePressed

    private void jPanelStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStudentMousePressed
        pane2.setBackground(paneClick);
        pane1.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);
        JOptionPane.showMessageDialog(this, "Login with \"Đào Tạo\" account to use this function");
    }//GEN-LAST:event_jPanelStudentMousePressed

    private void jPanelRatingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRatingMousePressed
        pane4.setBackground(paneClick);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane1.setBackground(panedefault);
        jDesktopPane1.removeAll();
        Statistical_Jint rt = new Statistical_Jint();
        jDesktopPane1.add(rt).setVisible(true);
    }//GEN-LAST:event_jPanelRatingMousePressed


    private void jPanelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseEntered
        jPanelHome.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_jPanelHomeMouseEntered

    private void jPanelStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStudentMouseEntered
        jPanelStudent.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_jPanelStudentMouseEntered

    private void jPanelRatingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRatingMouseEntered
        jPanelRating.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_jPanelRatingMouseEntered

    private void jPanelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseExited
        jPanelHome.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_jPanelHomeMouseExited

    private void jPanelStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStudentMouseExited
        jPanelStudent.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_jPanelStudentMouseExited

    private void jPanelRatingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRatingMouseExited
        jPanelRating.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_jPanelRatingMouseExited

    private void jPanelLearningMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLearningMouseEntered
        jPanelLearning.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_jPanelLearningMouseEntered

    private void jPanelLearningMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLearningMouseExited
        jPanelLearning.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_jPanelLearningMouseExited

    private void jPanelLearningMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLearningMousePressed
        pane3.setBackground(paneClick);
        pane2.setBackground(panedefault);
        pane4.setBackground(panedefault);
        pane1.setBackground(panedefault);
        jDesktopPane1.removeAll();
        QL_Diem_Jint qd = new QL_Diem_Jint();
        jDesktopPane1.add(qd).setVisible(true);
    }//GEN-LAST:event_jPanelLearningMousePressed

    private void lblScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScreenMousePressed
        if (this.getExtendedState() != QuanLyDiem.MAXIMIZED_BOTH) {
            this.setExtendedState(QuanLyDiem.MAXIMIZED_BOTH);

        } else {
            this.setExtendedState(QuanLyDiem.NORMAL);
        }
        JOptionPane.showMessageDialog(this, "Is in the process of finishing", "Message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_lblScreenMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        this.setExtendedState(QuanLyDiem.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to change account?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            QuanLyDiem.this.dispose();;
        } else {
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to change your password?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            new ChangePassWord().setVisible(true);
            QuanLyDiem.this.dispose();;
        } else {
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
       new SendMail1().setVisible(true);
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLearning;
    private javax.swing.JPanel jPanelRating;
    private javax.swing.JPanel jPanelStudent;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLearning;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblScreen;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JPanel pane3;
    private javax.swing.JPanel pane4;
    // End of variables declaration//GEN-END:variables
}
